schema: "classroom50/repo-config/v1"
classroom: "etc5523"
assignment: "assignment-3"
owner:
  username: "shee0080"
  id: 264734107
  accepted_at: "2026-10-02T06:08:34Z"
source:
  owner: "ETC5523-2026"
  owner_id: 265932295
  repo: "assignment-3"
  branch: "main"
