project:
  type: website

website:
  title: "Shenyu He's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
    right:
      - icon: github
        href: https://github.com/shee0080

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


